# Generated by Django 4.0.3 on 2022-05-01 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20, null=True)),
                ('gnd', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'FEMALE'), (2, 'MALE'), (3, 'OTHER')], max_length=5)),
                ('ph_no', models.CharField(max_length=15, unique=True)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('specialist', models.CharField(max_length=20)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdate', models.DateTimeField()),
                ('stime', models.DateTimeField()),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chms.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('dob', models.DateField(null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('blood_grp', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'A+'), (2, 'A-'), (3, 'B+'), (4, 'B−'), (5, 'AB+'), (6, 'AB−'), (7, 'O+'), (8, 'O−')], max_length=15, null=True)),
                ('gnd', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'FEMALE'), (2, 'MALE'), (3, 'OTHER')], max_length=5)),
                ('ph_no', models.CharField(max_length=15, unique=True)),
                ('email_id', models.EmailField(max_length=50, unique=True)),
                ('vacc_sts', models.CharField(max_length=20)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chms.doctor')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=50)),
                ('room_type', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'PRIVATE ROOM'), (2, 'EMEREGENCY WARD'), (3, 'COVID-19 WARD'), (4, '3-BED SHARED')], max_length=7)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chms.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_date', models.DateField(null=True)),
                ('app_time', models.TimeField(null=True)),
                ('desc', models.TextField()),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='chms.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='chms.patient')),
            ],
        ),
    ]
