# Generated by Django 4.0.3 on 2022-05-03 18:20

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='vacc_sts',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'First Dose'), (2, 'Second Dose')], max_length=3),
        ),
    ]
