# Generated by Django 4.0.3 on 2022-05-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chms', '0004_alter_shift_sdate_alter_shift_stime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='sdate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='shift',
            name='stime',
            field=models.DateTimeField(),
        ),
    ]
